FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY machi/package.json machi/pnpm-lock.yaml ./

RUN pnpm install

EXPOSE 3000
ENV PORT=3000

CMD ["pnpm", "run", "dev"]
