"""make_event_raw_integration_id_nullable

Revision ID: b7a80cf1fb75
Revises: add_github_oauth
Create Date: 2025-10-26 21:04:48.632792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a80cf1fb75'
down_revision = 'add_github_oauth'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_raw', 'integration_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_raw', 'integration_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
